quill/web/blueprints/q/models.py
from quill.common.models import Document


def get_user_documents(user_id, limit=None):
    """
    Get all of the documents for a user
    """

    results = Document.objects(
        user_id=user_id
    ).order_by('-date_created')

    if limit:
        # Apply the limit
        results = results[:limit]

    return results


def get_user_document(user_id, doc_id):
    """
    Get a single document for a user
    """

    return Document.objects(
        id=doc_id,
        user_id=user_id
    ).first()


def delete_user_documents(user_id):
    """
    Delete all of the documents for a user
    """

    return Document.objects(
        user_id=user_id
    ).delete()


def delete_user_document(user_id, doc_id):
    """
    Delete a document for a user
    """

    return Document.objects(
        id=doc_id,
        user_id=user_id
    ).delete()

quill/web/blueprints/q/forms.py
import os

from flask.ext.wtf import Form, FileField
from flask.ext.wtf import Required
from wtforms import ValidationError

EMPTY_LABEL = ''


class UploadDocumentForm(Form):

    file = FileField(
        EMPTY_LABEL,
        validators=[
            Required(),
        ]
    )

    def validate_file(form, field):
        """
        Validate the Word or text extension
        """

        if field.data:
            name, extension = os.path.splitext(
                str(field.data).lower()
            )

            if not extension in ['.doc', '.docx', '.txt']:
                raise ValidationError("Invalid file type: '%s'" % extension)
        else:
            raise ValidationError('Missing file data.')

quill/web/blueprints/q/__init__.py
from flask import Blueprint

q = Blueprint(
    'q',
    __name__,
    template_folder='templates',
    static_folder='assets'
)

quill/web/blueprints/q/views.py
from . import q

from flask import render_template, request, current_app as app
from flask.ext.login import login_required, current_user
from flask.views import MethodView

from quill.common.models import Document
from quill.web.blueprints.q.forms import UploadDocumentForm
from quill.web.blueprints.q.models import (
    get_user_documents, get_user_document,
    delete_user_documents, delete_user_document,
)
from quill.web.core.responses import (
    Success, InternalServerError,
    NotFound, BadRequest
)

@q.route("/")
@login_required
def index():
    """
    Serve the app context
    """

    context = {
        'user': current_user,
        'form': UploadDocumentForm(),
        'documents': get_user_documents(
            current_user.id, limit=5
        )
    }
    return render_template('app.html', **context)


@q.route("/documents")
@login_required
def documents():
    """
    Load the documents for a user
    """

    context = {
        'user': current_user,
        'documents': get_user_documents(
            current_user.id
        )
    }
    return render_template('documents.html', **context)


@q.route("/documents/<string:id>")
@login_required
def document(id):
    """
    Load the document for a user
    """

    context = {
        'user': current_user,
        'doc': get_user_document(
            current_user.id, id
        )
    }
    return render_template('document.html', **context)

@q.route("/help")
@login_required
def help():
    """
    Provide help to the user
    """

    context = {}
    return render_template('help.html', **context)


#
# API Endpoints (JSON)
#

class DocumentAPI(MethodView):
    decorators = [login_required]

    def get(self, id):
        try:
            if id is None:
                # Return the list
                result = get_user_documents(
                    current_user.id
                )
            else:
                # Return the single document
                result = get_user_document(
                    current_user.id, id
                )

            if result:
                return Success(result.to_json())
            else:
                return NotFound(errors=None)
        except Exception as e:
            app.logger.error(e)
            return InternalServerError(e)

    def delete(self, id=None):
        try:
            if id is None:
                # Delete the list
                delete_user_documents(
                    current_user.id
                )
            else:
                # Delete the single document
                delete_user_document(
                    current_user.id, id
                )

            return Success()
        except Exception as e:
            app.logger.error(e)
            return InternalServerError(e)

    def post(self):
        form = UploadDocumentForm(request.form)
        app.logger.debug('Files: %s', request.files)

        if 'file' in request.files:
            try:
                # Get the file, parse it
                # and get recommendations
                doc = Document.from_file(
                    current_user.id,
                    request.files['file']
                )

                app.logger.debug(
                    doc.to_json(indent=2)
                )

                # Return the recommendations
                return Success(doc.to_json())
            except Exception as e:
                app.logger.error(e)
                return InternalServerError(str(e))
        else:
            app.logger.error(form.errors)
            return BadRequest(form.errors)

quill/web/blueprints/q/templates/app.html
{% extends "app_base.html" %}

{% block title %}{% endblock %}

{% block nav %}
    {% include "snippets/app_nav.html" %}
{% endblock %}

{% block content %}
<h2>Home</h2>
<hr/>

{% include "snippets/flashes.html" %}

<div class="row-fluid">
    <h3>Your Recent Documents</h3>
    <ul class="documents-list">
    {% if documents %}

        {% for doc in documents %}
            <li>
                <a href="{{ url_for('q.document', id=doc.id) }}">{{ doc.filename }}</a>
                {{ doc.date_created|timesince }}
                <button class="delete-doc-btn" data-id="{{ doc.id }}">Delete</button>
            </li>
        {% endfor %}
    {% else %}
        <li class="warning">You have no documents yet!</li>
    {% endif %}
    </ul>
</div>

<br/>

<div class='row-fluid'>
    <h3>Analyze A New Document</h3>

    <form id="upload" method="post" action="{{ url_for('document_api') }}" enctype="multipart/form-data">
        <div class="analyzing">Analyzing...</div>
        {{ form.hidden_tag() }}
        <input type="file" id="file" name="file"/>
    </form>

    <br>
</div>
{% endblock %}

{% block page_js %}

{% endblock %}

quill/web/blueprints/q/templates/document.html
{% extends "app_base.html" %}

{% block title %}- Document{% endblock %}

{% block nav %}
    {% include "snippets/app_nav.html" %}
{% endblock %}

{% block content %}
<h2>Document</h2>

<button class="delete-doc-btn" data-id="{{ doc.id }}">Delete</button>
<hr/>

{% include "snippets/flashes.html" %}


<div class='row-fluid'>
    <h3><strong>{{ doc.filename }} - {{ doc.date_created|timesince }}</strong></h3>
    <div id="viewer">

    </div>
 </div>


{% if doc %}
    <p><strong>Document Summary</strong></p>
    <ul>
        <li>Paragraphs: {{ doc.summary.paragraphs }}</li>
        <li>Sentences: {{ doc.summary.sentences }}</li>
        <li>Words: {{ doc.summary.words }}</li>
        <li>Syllables: {{ doc.summary.syllables }}</li>
        <li>Complex Words: {{ doc.summary.complex_words }}</li>
        <li>Characters: {{ doc.summary.characters }}</li>
    </ul>

    <p><strong>Style Summary</strong></p>
    <ul>
        <li>Avg. Words Per Paragraph: {{ doc.summary.avg_words_per_paragraph|round(1) }}</li>
        <li>Avg. Words Per Sentence: {{ doc.summary.avg_words_per_sentence|round(1) }}</li>
        <li>Avg. Sentences Per Paragraph: {{ doc.summary.avg_sentences_per_paragraph|round(1) }}</li>
        <li>Avg. Characters Per Word: {{ doc.summary.avg_characters_per_word|round(1) }}</li>
        <li>Avg. Syllables Per Word: {{ doc.summary.avg_syllables_per_word|round(1) }}</li>
        <li>Avg. Syllables Per Sentence: {{ doc.summary.avg_syllables_per_sentence|round(1) }}</li>
        <li>Avg. Syllables Per Paragraph: {{ doc.summary.avg_syllables_per_paragraph|round(1) }}</li>
    </ul>

    <p><strong>Readability Summary</strong></p>
    <ul>
         <li>Automated Readability Index: {{ doc.readability.ARI|round(1) }}</li>
         <li>Coleman Liau Index: {{ doc.readability.CLI|round(1) }}</li>
         <li>Flesch Kincaid Grade Level: {{ doc.readability.FKGL|round(1) }}</li>
         <li>Flesch Reading Ease: {{ doc.readability.FRE|round(1) }}</li>
         <li>Gunning Fog Index: {{ doc.readability.GFI|round(1) }}</li>
         <li>LIX: {{ doc.readability.LIX|round(1) }}</li>
         <li>RIX: {{ doc.readability.RIX|round(1) }}</li>
         <li>McAlpine EFLAW: {{ doc.readability.MEFLAW|round(1) }}</li>
         <li>SMOG Index: {{ doc.readability.SMOG|round(1) }}</li>
    </ul>

    <p><strong>Writing Recommendations</strong></p>
    {% if doc.recommendations %}
        <ul>
            {% for rr in doc.recommendations %}
            <li>
                <p><strong>{{ rr.name }}</strong> - {{ rr.message }}</p>

                {% if rr.applies_to %}
                    <p>Applies to:</p>
                    <ul>
                        {% for atom in rr.applies_to %}
                            <li>{{ atom._cls }} - {{ atom.text }} ({{ atom.pid }}, {{ atom.sid }})</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Looks good!</p>
    {% endif %}

{% else %}
    <p>Missing document!</p>
{% endif %}

{% endblock %}


{% block page_js %}
<script>
    var app = new AppView({
       'id': '{{ doc.id|safe }}',
       'paragraphs': {{ doc.paragraphs|tojson|safe }},
       'sentences': {{ doc.sentences|tojson|safe }} //,
    {#}//'recommendations': {{ doc.recommendations|tojson|safe }} #}
    });
</script>
{% endblock %}

quill/web/blueprints/q/templates/documents.html
{% extends "app_base.html" %}

{% block title %}- Documents{% endblock %}

{% block nav %}
    {% include "snippets/app_nav.html" %}
{% endblock %}

{% block content %}
<h2>Documents</h2>
<button class="delete-all-btn">Delete All</button>
<hr/>

{% include "snippets/flashes.html" %}

<ul class="documents-list">
{% if documents %}
    {% for doc in documents %}
        <li>
            <a href="{{ url_for('q.document', id=doc.id) }}">{{ doc.filename }}</a>
            {{ doc.date_created|timesince }}
            <button class="delete-doc-btn" data-id="{{ doc.id }}">Delete</button>
        </li>
    {% endfor %}
{% else %}
    <li class="warning">You have no documents yet!</li>
{% endif %}
</ul>

{% endblock %}

quill/web/blueprints/q/templates/help.html
{% extends "app_base.html" %}

{% block title %}- Help{% endblock %}

{% block nav %}
    {% include "snippets/app_nav.html" %}
{% endblock %}

{% block content %}
<h2>Help</h2>
<hr/>

{% include "snippets/flashes.html" %}

{% endblock %}