quill/web/blueprints/account/forms.py
from flask.ext.wtf import Form, TextField, BooleanField
from flask.ext.wtf import Required
import re
from wtforms import PasswordField
from wtforms.validators import Email, EqualTo, ValidationError

from quill.web.blueprints.account.messages import (
    MSG_WEAK_PASSWORD, MSG_PASSWORDS_MUST_MATCH
)


class StrongPassword(object):
    """
    Validator that checks that a password is strong
    """

    def __init__(self, message=None):
        if not message:
            message = MSG_WEAK_PASSWORD
        self.message = message

    def __call__(self, form, field):
        """
        Validate the field
        """

        if not self.is_strong_password(field.data):
            raise ValidationError(self.message)

    def is_strong_password(self, password):
        """
        Determine if a password is strong

        Current rules:
            Password must be a minimum of six characters in length,
            at least one letter and one number,
            and contain at least four different characters
        """

        return bool(
            len(password) >= 6 and
            re.findall('\d', password) and
            re.findall('[A-Za-z]', password) and
            len(set(password)) >= 4
        )


class LoginForm(Form):
    email_address = TextField(
        'Email Address',
        validators=[
            Required(),
            Email()
        ]
    )

    password = PasswordField('Password', validators=[Required()])
    remember_me = BooleanField('Remember Me', default=False)


class ChangePasswordForm(Form):
    password = PasswordField(
        'New Password',
        validators=[
            Required(),
            EqualTo('password_confirm', message=MSG_PASSWORDS_MUST_MATCH),
            StrongPassword()
        ]
    )

    password_confirm = PasswordField(
        'Confirm New Password',
        validators=[
            Required(),
            StrongPassword()
        ]
    )


class ResetPasswordForm(Form):
    email_address = TextField(
        'Email Address',
        validators=[
            Required()
        ]
    )


class SignupForm(Form):
    email_address = TextField(
        'Email Address',
        validators=[
            Required(),
            Email()
        ]
    )

    password = PasswordField(
        'Password',
        validators=[
            Required(),
            EqualTo('password_confirm', message=MSG_PASSWORDS_MUST_MATCH),
            StrongPassword()
        ]
    )

    password_confirm = PasswordField(
        'Confirm Password',
        validators=[
            Required(),
            StrongPassword()
        ]
    )


class SignupInviteCodeForm(SignupForm):
    invite_code = TextField(
        'Invite Code',
        validators=[
            Required()
        ]
    )


class DeleteAccountForm(Form):
    acknowledgement = BooleanField(
        'I acknowledge that deleting my account is permanent.',
        default=False,
        validators=[
            Required()
        ]
    )


class ActivationCodeForm(Form):
    activation_code = TextField(
        'Activation Code',
        validators=[
            Required()
        ]
    )


class WelcomeCodeForm(Form):
    welcome_code = TextField(
        'Welcome Code',
        validators=[
            Required()
        ]
    )

quill/web/blueprints/account/__init__.py
from flask import Blueprint

account = Blueprint(
    'account',
    __name__,
    template_folder='templates',
    static_folder='assets'
)

quill/web/blueprints/account/views.py
from . import account

from flask import (
    render_template, redirect,
    url_for, request, session, flash,
)

from flask.ext.login import (
    logout_user,
    login_required,
    login_user,
)

from flask.views import MethodView
from quill.web.core.responses import (
    Success, InternalServerError, BadRequest
)

from quill.web.blueprints.account.forms import (
    LoginForm, ChangePasswordForm,
    ResetPasswordForm, SignupForm,
    SignupInviteCodeForm,
    ActivationCodeForm,
    DeleteAccountForm
)

from quill.web.blueprints.account.messages import (
    MSG_INVALID_ACTIVATION_CODE,
    MSG_USER_ACTIVATED, MSG_USER_LOGIN,
    MSG_MISSING_ACTIVATION_CODE
)

from quill.web.blueprints.account.models import (
    authenticate, create_user,
    is_valid_activation_code, delete_account,
    update_password,
    update_plan
)


@account.route('/signup', methods=['GET', 'POST'])
def signup():
    """
    Provide a view for a new user to signup
    """

    # Bind the form to the request
    form = SignupForm(request.form)

    if form.validate_on_submit():
        # Get form fields
        email_address = form.email_address.data
        password = form.password.data

        # Create the new user
        user, message = create_user(email_address, password)

        if user:
            # Direct user to activate their account
            return redirect(url_for('account.activate'))
        else:
            # Flash the reason the account was not created
            flash(message, category="alert-error")

    return render_template('signup.html', form=form)


@account.route('/signup-code', methods=['GET', 'POST'])
def signup_with_code():
    """
    Provide a view for a new user
    to signup with a code
    """

    # Bind the form to the request
    form = SignupInviteCodeForm(request.form)

    if form.validate_on_submit():
        # Get form fields
        email_address = form.email_address.data
        password = form.password.data
        invite_code = form.invite_code.data

        # Create the new user
        user, message = create_user(email_address, password, invite_code)

        if user:
            # Direct user to activate their account
            return redirect(url_for('account.activate'))
        else:
            # Flash the reason the account was not created
            flash(message, category="alert-error")

    return render_template('signup_with_code.html', form=form)


@account.route('/activate', methods=['GET', 'POST'])
def activate():
    """
    Provide a view for a user to activate their account
    via email link or manually
    """

    # Bind the form to the request
    form = ActivationCodeForm(request.form)

    activation_code = None
    if request.method == "GET":
        # Handle the GET case where there may be
        # a code from an email link
        activation_code = request.args.get('code', None)

    elif form.validate_on_submit():
        # Get the code from the POST
        activation_code = form.activation_code.data

    # If no code at this point, remind the user to check their email
    if not activation_code:
        flash(MSG_MISSING_ACTIVATION_CODE, category='alert-info')
        context = {"form": form}

        return render_template('activate.html', **context)

    # Validate the code
    if is_valid_activation_code(activation_code):
        # Success: Either log the person in for
        # the first time, or redirect them to the login page

        flash(MSG_USER_ACTIVATED, category='alert-success')
        return redirect(url_for('account.login'))
    else:
        # Error
        flash(MSG_INVALID_ACTIVATION_CODE, category='alert-error')

    context = {"form": form}

    return render_template('activate.html', **context)


@account.route('/login', methods=['GET', 'POST'])
def login():
    """
    Provide a view for a user to login
    """

    # Bind the form to the request
    form = LoginForm(request.form)

    if form.validate_on_submit():
        # Get form fields
        email_address = form.email_address.data
        password = form.password.data
        remember_me = form.remember_me.data

        # Authenticate the user
        user, message = authenticate(email_address, password)

        # If the user is valid, let them in
        if user and login_user(user, remember=remember_me):
            # Set additional session variables
            # TODO: Encrypt the session
            session['email_address'] = user.email_address

            session.modified = True
            session.permanent = True

            flash(MSG_USER_LOGIN, category='alert-success')

            #if user.admin:
                # Redirect the user to the admin
            #    return redirect(url_for('admin.dashboard'))

            # Redirect the user to the app
            return redirect(url_for('q.index'))
        else:
            # Flash the reason they were not logged in
            flash(message, category="alert-error")

    return render_template('login.html', form=form)


@account.route('/password/change', methods=['GET', 'POST'])
@login_required
def change_password():
    """
    Allow a user to change their password if they know
    their existing password
    """

    # Bind the form to the request
    form = ChangePasswordForm(request.form)

    if form.validate_on_submit():
        # Get form fields
        password = form.password.data

        is_changed, message = update_password(
            session['email_address'], password
        )

        if not is_changed:
            # Flash the reason the password was not changed
            flash(message, category="alert-error")
            show_form = True
        else:
            flash(message, category="alert-success")
            show_form = False
    else:
        show_form = True

    context = {
        'show_form': True if request.method == 'GET' else show_form,
        'form': form
    }

    return render_template('change_password.html', **context)


@account.route('/password/reset', methods=['GET', 'POST'])
def reset_password():
    """
    Allow a user to reset their password if they have
    forgotten it
    """

    # Bind the form to the request
    form = ResetPasswordForm(request.form)

    if form.validate_on_submit():
        # Get form fields
        email_address = form.email_address.data

        is_reset, message = update_password(
            email_address, None, reset=True
        )

        if not is_reset:
            # Flash the reason the password was not reset
            flash(message, category="alert-error")
            show_form = True
        else:
            flash(message, category="alert-success")
            show_form = False

    context = {
        'show_form': True if request.method == 'GET' else show_form,
        'form': form
    }

    return render_template('reset_password.html', **context)


@account.route('/logout', methods=['GET'])
@login_required
def logout():
    """
    Log a user out of the system
    """

    logout_user()
    session.clear()

    return redirect(url_for('site.index'))

# TODO: Make this an API
@account.route('/delete', methods=['GET', 'POST'])
@login_required
def delete():
    """
    Provide a view for an existing user to delete their account
    """

    # Bind the form to the request
    form = DeleteAccountForm(request.form)

    if form.validate_on_submit():
        email_address = session['email_address']
        password = form.password.data

        # Delete the user account
        is_deleted, message = delete_account(email_address, password)

        if not is_deleted:
            # Flash the reason they were not cancelled
            flash(message, category="alert-error")
        else:
            # Log them out, clear the session
            logout_user()
            session.clear()

            return redirect(url_for('site.index'))

    return render_template('delete.html', form=form)


#
# API Endpoints (JSON)
#

class ChangePasswordAPI(MethodView):
    decorators = [login_required]

    def put(self):
        form = ChangePasswordForm(request.form)

        if form.validate():
            # Get form fields
            password = form.password.data

            is_changed, message = update_password(
                session['email_address'], password
            )
            if is_changed:
                return Success()
            else:
                return InternalServerError(message)
        else:
            return BadRequest(form.errors)


class PlanAPI(MethodView):
    decorators = [login_required]

    def _charge(self, plan, token):
        is_charged, message = update_plan(
            session['email_address'],
            int(plan),
            token
        )

        if is_charged:
            return Success()
        else:
            return InternalServerError(message)

    def put(self):
        return self._charge(
            request.form.get('planType', None),
            request.form.get('stripeToken', None)
        )

    def post(self):
        return self._charge(
            request.form.get('planType', None),
            request.form.get('stripeToken', None)
        )


class DeleteAccountAPI(MethodView):
    decorators = [login_required]

    def delete(self):
        email_address = session['email_address']

        # Delete the user account
        is_deleted, message = delete_account(email_address)

        if is_deleted:
            # Log them out, clear the session
            logout_user()
            session.clear()

            return Success()
        else:
            return InternalServerError(message)

quill/web/blueprints/account/templates/activate.html
{% extends "site_base.html" %}

{% block title %}- Activate Your Account{% endblock %}

{% block content %}
    <p>Activate Your Account</p>

    <ul>
        <li><a href="{{ url_for('account.reset_password') }}">Forgot your password?</a></li>
    </ul>

    {% include "snippets/flashes.html" %}

    <form method="POST" action="{{ url_for('account.activate') }}">
        {{ form.hidden_tag() }}
        {{ wtf.form_errors(form, "only") }}

        {{ wtf.horizontal_field(form.activation_code) }}

        <button id="activate-btn" name="activate-btn" type="submit">Activate</button>
    </form>

{% endblock %}

quill/web/blueprints/account/templates/change_password.html
{% extends "site_base.html" %}

{% block title %}- Change Your Password{% endblock %}
{% block content %}
    <p>Change Your Password</p>

    {% include "snippets/flashes.html" %}

    <form method="POST" action="{{ url_for('account.change_password') }}">
        {{ form.hidden_tag() }}
        {{ wtf.form_errors(form, "only") }}

        {{ wtf.horizontal_field(form.password) }}
        {{ wtf.horizontal_field(form.password_confirm) }}

        <button id="change-password-btn" name="change-password-btn" type="submit">Change Password</button>
    </form>

{% endblock %}

quill/web/blueprints/account/templates/delete.html
{% extends "site_base.html" %}

{% block title %}- Delete Your Account{% endblock %}
{% block content %}
    <p>Delete Your Account</p>

    {% include "snippets/flashes.html" %}

    <form method="POST" action="{{ url_for('account.delete') }}">
        {{ form.hidden_tag() }}
        {{ wtf.form_errors(form, "only") }}

        {{ wtf.horizontal_field(form.email_address) }}
        {{ wtf.horizontal_field(form.password) }}
        {{ wtf.horizontal_field(form.acknowledgement) }}

        <button id="cancel-btn" name="cancel-btn" type="submit">Delete Account</button>
    </form>

{% endblock %}

quill/web/blueprints/account/templates/login.html
{% extends "site_base.html" %}

{% block title %}- Login{% endblock %}
{% block content %}
    <p>Login</p>

    <ul>
        <li><a href="{{ url_for('account.reset_password') }}">Forgot your password?</a></li>
    </ul>

    {% include "snippets/flashes.html" %}

    <form method="POST" action="{{ url_for('account.login') }}">
        {{ form.hidden_tag() }}
        {{ wtf.form_errors(form, "only") }}

        {{ wtf.horizontal_field(form.email_address) }}
        {{ wtf.horizontal_field(form.password) }}
        {# {{ wtf.horizontal_field(form.remember_me) }} #}

        <button id="login-btn" name="login-btn" type="submit">Login</button>
    </form>

{% endblock %}

quill/web/blueprints/account/templates/reset_password.html
{% extends "site_base.html" %}

{% block title %}- Reset Your Password{% endblock %}
{% block content %}
    <p>Reset Your Password</p>

    <ul>
        <li><a href="{{ url_for('account.login') }}">Want to login instead?</a></li>
    </ul>

    {% include "snippets/flashes.html" %}

    <form method="POST" action="{{ url_for('account.reset_password') }}">
        {{ form.hidden_tag() }}
        {{ wtf.form_errors(form, "only") }}

        {{ wtf.horizontal_field(form.email_address) }}

        <button id="reset-password-btn" name="reset-password-btn" type="submit">Reset Your Password</button>
    </form>

{% endblock %}

quill/web/blueprints/account/templates/signup.html
{% extends "site_base.html" %}

{% block title %}- Sign Up For An Account{% endblock %}
{% block content %}
    <p>Sign Up For An Account</p>

    <ul>
        <li><a href="{{ url_for('account.login') }}">Already have an account?</a></li>
    </ul>

    {% include "snippets/flashes.html" %}

    <form method="POST" action="{{ url_for('account.signup') }}">
        {{ form.hidden_tag() }}
        {{ wtf.form_errors(form, "only") }}

        {{ wtf.horizontal_field(form.email_address) }}
        {{ wtf.horizontal_field(form.password) }}
        {{ wtf.horizontal_field(form.password_confirm) }}

        <button id="sign-up-btn" name="sign-up-btn" type="submit">Sign Up</button>
    </form>

{% endblock %}

quill/web/blueprints/account/templates/signup_with_code.html
{% extends "site_base.html" %}

{% block title %}- Sign Up For An Account{% endblock %}
{% block content %}
    <p>Sign Up For An Account</p>

    <ul>
        <li><a href="{{ url_for('account.login') }}">Already have an account?</a></li>
    </ul>

    {% include "snippets/flashes.html" %}

    <form method="POST" action="{{ url_for('account.signup_with_code') }}">
        {{ form.hidden_tag() }}
        {{ wtf.form_errors(form, "only") }}

        {{ wtf.horizontal_field(form.email_address) }}
        {{ wtf.horizontal_field(form.password) }}
        {{ wtf.horizontal_field(form.password_confirm) }}

        {{ wtf.horizontal_field(form.invite_code) }}

        <button id="sign-up-btn" name="sign-up-btn" type="submit">Sign Up</button>
    </form>

{% endblock %}